name: Release
on: push

jobs:
  test:
    name: Deploy release to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Get the version
        id: get_version
        run: echo ::set-env name=GHA_TAG_VERSION::${GITHUB_REF#refs/tags/}
      - name: Get the SHA1 of the git commit
        id: get_hash
        run: echo ::set-env name=GHA_GIT_COMMIT::${GITHUB_SHA}
      - name: Build package
        run: |
          python setup.py sdist 
          python setup.py bdist_wheel --universal
      - name: Run tests
        run: |
          python -m pip install matplotlib
          python -m pip install --no-index --find-links=dist monashspa
          python -m monashspa.tests
      - name: Publish package to test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish package to main PyPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_MASTER }}